#!/usr/bin/env python3
"""Fold-aware inference for frozen SCORPION cross-fold metrics.

The historical analyzer treated 48 slide summaries as independent even though
slides within a test fold share trained models and probes. This v2 analysis uses
a two-stage fold/slide cluster bootstrap and reports no slide-level sign-flip
p-values.

Input is ``raw_slide_metrics.csv`` generated by the existing metric extractor.
No historical confidence interval or p-value is promoted automatically.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

METRICS = (
    "scanner_probe_accuracy",
    "pair_cosine_average",
    "pair_cosine_worst",
    "retrieval_top1_average",
    "retrieval_top1_worst",
)
LOWER_IS_BETTER = {"scanner_probe_accuracy"}


class AnalysisError(RuntimeError):
    pass


def load_contrasts(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    required = {"fold", "variant", "seed", "slide_id", *METRICS}
    missing = sorted(required - set(frame.columns))
    if missing:
        raise AnalysisError(f"missing columns: {missing}")
    if frame.duplicated(["fold", "variant", "seed", "slide_id"]).any():
        raise AnalysisError("duplicate fold/variant/seed/slide rows")

    seed_averaged = frame.groupby(["fold", "variant", "slide_id"], as_index=False)[
        list(METRICS)
    ].mean()
    paired = seed_averaged[seed_averaged["variant"] == "paired_reference"].set_index(
        ["fold", "slide_id"]
    )
    factorized = seed_averaged[seed_averaged["variant"] == "pathoalign_dep20"].set_index(
        ["fold", "slide_id"]
    )
    if set(paired.index) != set(factorized.index):
        raise AnalysisError("methods do not share identical fold/slide blocks")
    if len(paired) != 48 or paired.index.get_level_values("fold").nunique() != 5:
        raise AnalysisError("expected 48 slides across five folds")

    rows = []
    for fold, slide_id in paired.index:
        row = {"fold": int(fold), "slide_id": str(slide_id)}
        for metric in METRICS:
            row[metric] = float(
                factorized.loc[(fold, slide_id), metric] - paired.loc[(fold, slide_id), metric]
            )
        rows.append(row)
    return pd.DataFrame(rows).sort_values(["fold", "slide_id"])


def two_stage_cluster_bootstrap(
    contrasts: pd.DataFrame,
    metric: str,
    *,
    seed: int,
    draws: int,
) -> np.ndarray:
    rng = np.random.default_rng(seed)
    folds = np.asarray(sorted(contrasts["fold"].unique()))
    groups = {
        int(fold): contrasts.loc[contrasts["fold"] == fold, metric].to_numpy(float)
        for fold in folds
    }
    values = np.empty(draws, dtype=float)
    for draw in range(draws):
        sampled_folds = rng.choice(folds, size=len(folds), replace=True)
        sampled_values = []
        for fold in sampled_folds:
            group = groups[int(fold)]
            sampled_values.append(rng.choice(group, size=len(group), replace=True))
        values[draw] = float(np.concatenate(sampled_values).mean())
    return values


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw-slide-metrics", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--bootstrap-draws", type=int, default=100000)
    args = parser.parse_args()
    if args.bootstrap_draws < 1000:
        raise SystemExit("bootstrap-draws must be at least 1000")

    contrasts = load_contrasts(args.raw_slide_metrics)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    contrasts.to_csv(args.out_dir / "slide_seed_averaged_contrasts.csv", index=False)

    rows = []
    for index, metric in enumerate(METRICS):
        observed = contrasts[metric].to_numpy(float)
        bootstrap = two_stage_cluster_bootstrap(
            contrasts,
            metric,
            seed=20260725 + index,
            draws=args.bootstrap_draws,
        )
        favorable = observed < 0 if metric in LOWER_IS_BETTER else observed > 0
        fold_means = contrasts.groupby("fold")[metric].mean()
        rows.append(
            {
                "metric": metric,
                "difference_definition": "pathoalign_dep20_minus_paired_reference",
                "n_folds": int(contrasts["fold"].nunique()),
                "n_slides": int(len(contrasts)),
                "mean_difference": float(observed.mean()),
                "median_difference": float(np.median(observed)),
                "fold_mean_min": float(fold_means.min()),
                "fold_mean_max": float(fold_means.max()),
                "fraction_slides_favorable": float(np.mean(favorable)),
                "cluster_bootstrap_ci_025": float(np.quantile(bootstrap, 0.025)),
                "cluster_bootstrap_ci_975": float(np.quantile(bootstrap, 0.975)),
                "bootstrap_draws": args.bootstrap_draws,
                "p_value_reported": False,
            }
        )

    summary = pd.DataFrame(rows)
    summary.to_csv(args.out_dir / "fold_aware_contrasts.csv", index=False)
    design = {
        "status": "completed",
        "analysis_version": 2,
        "input": str(args.raw_slide_metrics.resolve()),
        "seed_averaging": "within fold/slide/method before contrast",
        "bootstrap": "resample folds, then slides within sampled folds",
        "n_folds": 5,
        "bootstrap_draws": args.bootstrap_draws,
        "sign_flip_p_values": "not reported",
        "claim_boundary": (
            "Intervals describe uncertainty under the observed five-fold design. "
            "Five folds remain a small number of training clusters, and repeated "
            "independent fold assignments would provide stronger confirmation."
        ),
    }
    (args.out_dir / "analysis_design.json").write_text(
        json.dumps(design, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"SCORPION FOLD-AWARE ANALYSIS V2 PASSED: {args.out_dir}")


if __name__ == "__main__":
    try:
        main()
    except (AnalysisError, OSError, ValueError) as exc:
        print(f"SCORPION FOLD-AWARE ANALYSIS V2 FAILED: {exc}")
        raise SystemExit(1) from exc
