"""Clinical report generation for Real-Time WSI Streaming.

Generates PDF reports with visualizations, confidence metrics, and processing metadata
for clinical use in hospital demos and production deployments.

Supports:
- Customizable report templates
- Multi-language support (i18n)
- Institutional branding
"""

import io
import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
from PIL import Image

# PDF generation
try:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.lib.pagesizes import A4, letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Image as RLImage
    from reportlab.platypus import (
        KeepTogether,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

logger = logging.getLogger(__name__)


# Default translations for supported languages
DEFAULT_TRANSLATIONS = {
    "en": {
        "report_title": "Real-Time WSI Analysis Report",
        "slide_information": "Slide Information",
        "slide_id": "Slide ID",
        "patient_id": "Patient ID",
        "report_date": "Report Date",
        "scan_date": "Scan Date",
        "analysis_results": "Analysis Results",
        "prediction": "Prediction",
        "confidence": "Confidence",
        "confidence_high": "High confidence",
        "confidence_medium": "Moderate confidence",
        "confidence_low": "Low confidence - manual review recommended",
        "uncertainty_score": "Uncertainty Score",
        "confidence_interval": "95% Confidence Interval",
        "visualizations": "Visualizations",
        "figure_heatmap": "Figure 1: Attention heatmap showing regions of diagnostic importance",
        "figure_confidence": "Figure 2: Confidence progression during real-time analysis",
        "no_visualizations": "No visualizations available",
        "quality_metrics": "Quality Metrics",
        "coverage": "Coverage",
        "patches_processed": "Patches Processed",
        "processing_time": "Processing Time",
        "throughput": "Throughput",
        "peak_memory": "Peak Memory Usage",
        "processing_metadata": "Processing Metadata",
        "model_version": "Model Version",
        "processing_mode": "Processing Mode",
        "analysis_timestamp": "Analysis Timestamp",
        "clinical_notes": "Clinical Notes",
        "physician_notes": "Physician Notes",
        "recommendations": "Recommendations",
        "disclaimer": "DISCLAIMER: This report is generated by an AI-assisted diagnostic system and should be used as a decision support tool only. All results must be reviewed and validated by a qualified healthcare professional. This system is not intended to replace clinical judgment.",
    },
    "es": {
        "report_title": "Informe de Análisis WSI en Tiempo Real",
        "slide_information": "Información de la Diapositiva",
        "slide_id": "ID de Diapositiva",
        "patient_id": "ID de Paciente",
        "report_date": "Fecha del Informe",
        "scan_date": "Fecha de Escaneo",
        "analysis_results": "Resultados del Análisis",
        "prediction": "Predicción",
        "confidence": "Confianza",
        "confidence_high": "Alta confianza",
        "confidence_medium": "Confianza moderada",
        "confidence_low": "Baja confianza - se recomienda revisión manual",
        "uncertainty_score": "Puntuación de Incertidumbre",
        "confidence_interval": "Intervalo de Confianza del 95%",
        "visualizations": "Visualizaciones",
        "figure_heatmap": "Figura 1: Mapa de calor de atención mostrando regiones de importancia diagnóstica",
        "figure_confidence": "Figura 2: Progresión de confianza durante el análisis en tiempo real",
        "no_visualizations": "No hay visualizaciones disponibles",
        "quality_metrics": "Métricas de Calidad",
        "coverage": "Cobertura",
        "patches_processed": "Parches Procesados",
        "processing_time": "Tiempo de Procesamiento",
        "throughput": "Rendimiento",
        "peak_memory": "Uso Máximo de Memoria",
        "processing_metadata": "Metadatos de Procesamiento",
        "model_version": "Versión del Modelo",
        "processing_mode": "Modo de Procesamiento",
        "analysis_timestamp": "Marca de Tiempo del Análisis",
        "clinical_notes": "Notas Clínicas",
        "physician_notes": "Notas del Médico",
        "recommendations": "Recomendaciones",
        "disclaimer": "DESCARGO DE RESPONSABILIDAD: Este informe es generado por un sistema de diagnóstico asistido por IA y debe usarse solo como herramienta de apoyo a la decisión. Todos los resultados deben ser revisados y validados por un profesional de la salud calificado. Este sistema no pretende reemplazar el juicio clínico.",
    },
    "fr": {
        "report_title": "Rapport d'Analyse WSI en Temps Réel",
        "slide_information": "Informations sur la Lame",
        "slide_id": "ID de Lame",
        "patient_id": "ID Patient",
        "report_date": "Date du Rapport",
        "scan_date": "Date de Numérisation",
        "analysis_results": "Résultats de l'Analyse",
        "prediction": "Prédiction",
        "confidence": "Confiance",
        "confidence_high": "Haute confiance",
        "confidence_medium": "Confiance modérée",
        "confidence_low": "Faible confiance - examen manuel recommandé",
        "uncertainty_score": "Score d'Incertitude",
        "confidence_interval": "Intervalle de Confiance à 95%",
        "visualizations": "Visualisations",
        "figure_heatmap": "Figure 1: Carte de chaleur d'attention montrant les régions d'importance diagnostique",
        "figure_confidence": "Figure 2: Progression de la confiance pendant l'analyse en temps réel",
        "no_visualizations": "Aucune visualisation disponible",
        "quality_metrics": "Métriques de Qualité",
        "coverage": "Couverture",
        "patches_processed": "Patchs Traités",
        "processing_time": "Temps de Traitement",
        "throughput": "Débit",
        "peak_memory": "Utilisation Maximale de la Mémoire",
        "processing_metadata": "Métadonnées de Traitement",
        "model_version": "Version du Modèle",
        "processing_mode": "Mode de Traitement",
        "analysis_timestamp": "Horodatage de l'Analyse",
        "clinical_notes": "Notes Cliniques",
        "physician_notes": "Notes du Médecin",
        "recommendations": "Recommandations",
        "disclaimer": "AVERTISSEMENT: Ce rapport est généré par un système de diagnostic assisté par IA et ne doit être utilisé que comme outil d'aide à la décision. Tous les résultats doivent être examinés et validés par un professionnel de santé qualifié. Ce système n'est pas destiné à remplacer le jugement clinique.",
    },
    "de": {
        "report_title": "Echtzeit-WSI-Analysebericht",
        "slide_information": "Objektträger-Informationen",
        "slide_id": "Objektträger-ID",
        "patient_id": "Patienten-ID",
        "report_date": "Berichtsdatum",
        "scan_date": "Scandatum",
        "analysis_results": "Analyseergebnisse",
        "prediction": "Vorhersage",
        "confidence": "Vertrauen",
        "confidence_high": "Hohes Vertrauen",
        "confidence_medium": "Mäßiges Vertrauen",
        "confidence_low": "Geringes Vertrauen - manuelle Überprüfung empfohlen",
        "uncertainty_score": "Unsicherheitswert",
        "confidence_interval": "95% Konfidenzintervall",
        "visualizations": "Visualisierungen",
        "figure_heatmap": "Abbildung 1: Aufmerksamkeits-Heatmap zeigt Bereiche diagnostischer Bedeutung",
        "figure_confidence": "Abbildung 2: Vertrauensentwicklung während der Echtzeitanalyse",
        "no_visualizations": "Keine Visualisierungen verfügbar",
        "quality_metrics": "Qualitätsmetriken",
        "coverage": "Abdeckung",
        "patches_processed": "Verarbeitete Patches",
        "processing_time": "Verarbeitungszeit",
        "throughput": "Durchsatz",
        "peak_memory": "Maximale Speichernutzung",
        "processing_metadata": "Verarbeitungsmetadaten",
        "model_version": "Modellversion",
        "processing_mode": "Verarbeitungsmodus",
        "analysis_timestamp": "Analyse-Zeitstempel",
        "clinical_notes": "Klinische Notizen",
        "physician_notes": "Arztnotizen",
        "recommendations": "Empfehlungen",
        "disclaimer": "HAFTUNGSAUSSCHLUSS: Dieser Bericht wird von einem KI-gestützten Diagnosesystem erstellt und sollte nur als Entscheidungshilfe verwendet werden. Alle Ergebnisse müssen von einem qualifizierten medizinischen Fachpersonal überprüft und validiert werden. Dieses System ist nicht dazu bestimmt, das klinische Urteilsvermögen zu ersetzen.",
    },
}


@dataclass
class ReportTemplate:
    """Configuration for report template customization."""

    # Layout
    page_size: str = "letter"  # 'letter', 'a4'
    margins: Dict[str, float] = field(
        default_factory=lambda: {"top": 0.75, "bottom": 0.75, "left": 0.75, "right": 0.75}
    )  # in inches

    # Typography
    title_font_size: int = 24
    section_font_size: int = 14
    body_font_size: int = 11

    # Colors (hex)
    primary_color: str = "#2c5aa0"
    confidence_high_color: str = "#2e7d32"
    confidence_medium_color: str = "#f57c00"
    confidence_low_color: str = "#c62828"

    # Sections to include
    include_patient_info: bool = True
    include_visualizations: bool = True
    include_quality_metrics: bool = True
    include_metadata: bool = True
    include_clinical_notes: bool = True
    include_disclaimer: bool = True

    # Custom sections (title: content)
    custom_sections: Dict[str, str] = field(default_factory=dict)


logger = logging.getLogger(__name__)


@dataclass
class StreamingReportData:
    """Data for streaming WSI clinical report."""

    # Patient/Slide info
    slide_id: str
    patient_id: Optional[str] = None
    scan_date: Optional[datetime] = None

    # Processing results
    prediction_class: str = ""
    confidence: float = 0.0
    processing_time: float = 0.0
    patches_processed: int = 0
    total_patches: int = 0

    # Attention data
    attention_heatmap_path: Optional[Path] = None
    confidence_plot_path: Optional[Path] = None

    # Quality metrics
    coverage_percent: float = 0.0
    throughput: float = 0.0
    memory_usage_gb: float = 0.0

    # Uncertainty quantification
    uncertainty_score: Optional[float] = None
    confidence_interval: Optional[tuple[float, float]] = None

    # Metadata
    model_version: str = "1.0.0"
    processing_mode: str = "streaming"
    report_timestamp: datetime = field(default_factory=datetime.now)

    # Clinical notes
    physician_notes: Optional[str] = None
    recommendations: List[str] = field(default_factory=list)


class StreamingReportGenerator:
    """Generate clinical reports for real-time WSI streaming results.

    Features:
    - PDF report templates with visualizations
    - Confidence metrics and uncertainty quantification
    - Processing metadata and quality metrics
    - Institutional branding support
    - Customizable report templates
    - Multi-language support (i18n)
    """

    def __init__(
        self,
        institution_name: str = "HistoCore Medical AI",
        institution_logo: Optional[Path] = None,
        template_config: Optional[ReportTemplate] = None,
        language: str = "en",
        custom_translations: Optional[Dict[str, Dict[str, str]]] = None,
    ):
        """Initialize report generator.

        Args:
            institution_name: Name of institution for branding
            institution_logo: Path to institution logo image
            template_config: Custom template configuration
            language: Language code ('en', 'es', 'fr', 'de')
            custom_translations: Custom translation dictionaries
        """
        if not REPORTLAB_AVAILABLE:
            raise ImportError(
                "reportlab required for PDF generation. Install with: pip install reportlab"
            )

        self.institution_name = institution_name
        self.institution_logo = institution_logo
        self.template = template_config or ReportTemplate()
        self.language = language

        # Setup translations
        self.translations = DEFAULT_TRANSLATIONS.copy()
        if custom_translations:
            self.translations.update(custom_translations)

        if language not in self.translations:
            logger.warning(f"Language '{language}' not supported, falling back to English")
            self.language = "en"

        # Setup styles
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

        logger.info(
            f"Initialized StreamingReportGenerator for {institution_name} (language: {self.language})"
        )

    def t(self, key: str) -> str:
        """Translate a key to the current language.

        Args:
            key: Translation key

        Returns:
            Translated string
        """
        return self.translations[self.language].get(key, key)

    def _setup_custom_styles(self):
        """Setup custom paragraph styles for reports."""
        # Title style
        self.styles.add(
            ParagraphStyle(
                name="CustomTitle",
                parent=self.styles["Heading1"],
                fontSize=self.template.title_font_size,
                textColor=colors.HexColor("#1a1a1a"),
                spaceAfter=30,
                alignment=TA_CENTER,
                fontName="Helvetica-Bold",
            )
        )

        # Section header style
        self.styles.add(
            ParagraphStyle(
                name="SectionHeader",
                parent=self.styles["Heading2"],
                fontSize=self.template.section_font_size,
                textColor=colors.HexColor(self.template.primary_color),
                spaceBefore=20,
                spaceAfter=12,
                fontName="Helvetica-Bold",
            )
        )

        # Metric style
        self.styles.add(
            ParagraphStyle(
                name="Metric",
                parent=self.styles["Normal"],
                fontSize=self.template.body_font_size,
                textColor=colors.HexColor("#333333"),
                spaceAfter=6,
            )
        )

        # Confidence high style
        self.styles.add(
            ParagraphStyle(
                name="ConfidenceHigh",
                parent=self.styles["Normal"],
                fontSize=18,
                textColor=colors.HexColor(self.template.confidence_high_color),
                fontName="Helvetica-Bold",
            )
        )

        # Confidence medium style
        self.styles.add(
            ParagraphStyle(
                name="ConfidenceMedium",
                parent=self.styles["Normal"],
                fontSize=18,
                textColor=colors.HexColor(self.template.confidence_medium_color),
                fontName="Helvetica-Bold",
            )
        )

        # Confidence low style
        self.styles.add(
            ParagraphStyle(
                name="ConfidenceLow",
                parent=self.styles["Normal"],
                fontSize=18,
                textColor=colors.HexColor(self.template.confidence_low_color),
                fontName="Helvetica-Bold",
            )
        )

    def generate_pdf_report(self, report_data: StreamingReportData, output_path: Path) -> Path:
        """Generate PDF clinical report.

        Args:
            report_data: Report data with results and visualizations
            output_path: Path to save PDF report

        Returns:
            Path to generated PDF file
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Determine page size
        page_size = A4 if self.template.page_size == "a4" else letter
        margins = self.template.margins

        # Create PDF document
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=page_size,
            rightMargin=margins["right"] * inch,
            leftMargin=margins["left"] * inch,
            topMargin=margins["top"] * inch,
            bottomMargin=margins["bottom"] * inch,
        )

        # Build report content
        story = []

        # Header
        story.extend(self._build_header(report_data))

        # Patient/Slide information
        if self.template.include_patient_info:
            story.extend(self._build_patient_info(report_data))

        # Primary results
        story.extend(self._build_results_section(report_data))

        # Visualizations
        if self.template.include_visualizations:
            story.extend(self._build_visualizations_section(report_data))

        # Quality metrics
        if self.template.include_quality_metrics:
            story.extend(self._build_quality_metrics(report_data))

        # Processing metadata
        if self.template.include_metadata:
            story.extend(self._build_metadata_section(report_data))

        # Clinical notes and recommendations
        if self.template.include_clinical_notes and (
            report_data.physician_notes or report_data.recommendations
        ):
            story.extend(self._build_clinical_notes(report_data))

        # Custom sections
        for section_title, section_content in self.template.custom_sections.items():
            story.append(Paragraph(section_title, self.styles["SectionHeader"]))
            story.append(Paragraph(section_content, self.styles["Normal"]))
            story.append(Spacer(1, 0.3 * inch))

        # Footer
        if self.template.include_disclaimer:
            story.extend(self._build_footer(report_data))

        # Build PDF
        doc.build(story)

        logger.info(f"Generated PDF report: {output_path}")
        return output_path

    def _build_header(self, report_data: StreamingReportData) -> List:
        """Build report header with institution branding."""
        elements = []

        # Institution logo if provided
        if self.institution_logo and self.institution_logo.exists():
            try:
                logo = RLImage(str(self.institution_logo), width=2 * inch, height=0.75 * inch)
                elements.append(logo)
                elements.append(Spacer(1, 0.2 * inch))
            except Exception as e:
                logger.warning(f"Failed to load institution logo: {e}")

        # Title
        title = Paragraph(
            f"<b>{self.institution_name}</b><br/>{self.t('report_title')}",
            self.styles["CustomTitle"],
        )
        elements.append(title)
        elements.append(Spacer(1, 0.3 * inch))

        return elements

    def _build_patient_info(self, report_data: StreamingReportData) -> List:
        """Build patient/slide information section."""
        elements = []

        elements.append(Paragraph(self.t("slide_information"), self.styles["SectionHeader"]))

        # Create info table
        data = [
            [f"{self.t('slide_id')}:", report_data.slide_id],
            [
                f"{self.t('report_date')}:",
                report_data.report_timestamp.strftime("%Y-%m-%d %H:%M:%S"),
            ],
        ]

        if report_data.patient_id:
            data.insert(1, [f"{self.t('patient_id')}:", report_data.patient_id])

        if report_data.scan_date:
            data.append([f"{self.t('scan_date')}:", report_data.scan_date.strftime("%Y-%m-%d")])

        table = Table(data, colWidths=[2 * inch, 4 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#555555")),
                    ("ALIGN", (0, 0), (0, -1), "RIGHT"),
                    ("ALIGN", (1, 0), (1, -1), "LEFT"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )

        elements.append(table)
        elements.append(Spacer(1, 0.3 * inch))

        return elements

    def _build_results_section(self, report_data: StreamingReportData) -> List:
        """Build primary results section with confidence."""
        elements = []

        elements.append(Paragraph(self.t("analysis_results"), self.styles["SectionHeader"]))

        # Prediction
        pred_text = f"<b>{self.t('prediction')}:</b> {report_data.prediction_class}"
        elements.append(Paragraph(pred_text, self.styles["Metric"]))
        elements.append(Spacer(1, 0.1 * inch))

        # Confidence with color coding
        confidence_pct = report_data.confidence * 100
        if report_data.confidence >= 0.90:
            style = "ConfidenceHigh"
            interpretation = self.t("confidence_high")
        elif report_data.confidence >= 0.70:
            style = "ConfidenceMedium"
            interpretation = self.t("confidence_medium")
        else:
            style = "ConfidenceLow"
            interpretation = self.t("confidence_low")

        conf_text = f"<b>{self.t('confidence')}:</b> {confidence_pct:.1f}%"
        elements.append(Paragraph(conf_text, self.styles[style]))
        elements.append(Paragraph(f"<i>{interpretation}</i>", self.styles["Normal"]))
        elements.append(Spacer(1, 0.1 * inch))

        # Uncertainty quantification if available
        if report_data.uncertainty_score is not None:
            unc_text = f"<b>{self.t('uncertainty_score')}:</b> {report_data.uncertainty_score:.3f}"
            elements.append(Paragraph(unc_text, self.styles["Metric"]))

        if report_data.confidence_interval:
            ci_low, ci_high = report_data.confidence_interval
            ci_text = f"<b>{self.t('confidence_interval')}:</b> [{ci_low:.3f}, {ci_high:.3f}]"
            elements.append(Paragraph(ci_text, self.styles["Metric"]))

        elements.append(Spacer(1, 0.3 * inch))

        return elements

    def _build_visualizations_section(self, report_data: StreamingReportData) -> List:
        """Build visualizations section with attention heatmap and confidence plot."""
        elements = []

        elements.append(Paragraph("Visualizations", self.styles["SectionHeader"]))

        viz_elements = []

        # Attention heatmap
        if report_data.attention_heatmap_path and report_data.attention_heatmap_path.exists():
            try:
                heatmap = RLImage(
                    str(report_data.attention_heatmap_path), width=5 * inch, height=4 * inch
                )
                viz_elements.append(heatmap)
                viz_elements.append(
                    Paragraph(
                        "<i>Figure 1: Attention heatmap showing regions of diagnostic importance</i>",
                        self.styles["Normal"],
                    )
                )
                viz_elements.append(Spacer(1, 0.2 * inch))
            except Exception as e:
                logger.warning(f"Failed to load attention heatmap: {e}")

        # Confidence progression plot
        if report_data.confidence_plot_path and report_data.confidence_plot_path.exists():
            try:
                conf_plot = RLImage(
                    str(report_data.confidence_plot_path), width=5 * inch, height=3 * inch
                )
                viz_elements.append(conf_plot)
                viz_elements.append(
                    Paragraph(
                        "<i>Figure 2: Confidence progression during real-time analysis</i>",
                        self.styles["Normal"],
                    )
                )
            except Exception as e:
                logger.warning(f"Failed to load confidence plot: {e}")

        if viz_elements:
            elements.extend(viz_elements)
        else:
            elements.append(Paragraph("<i>No visualizations available</i>", self.styles["Normal"]))

        elements.append(Spacer(1, 0.3 * inch))

        return elements

    def _build_quality_metrics(self, report_data: StreamingReportData) -> List:
        """Build quality metrics section."""
        elements = []

        elements.append(Paragraph("Quality Metrics", self.styles["SectionHeader"]))

        # Create metrics table
        data = [
            ["Coverage:", f"{report_data.coverage_percent:.1f}%"],
            [
                "Patches Processed:",
                f"{report_data.patches_processed:,} / {report_data.total_patches:,}",
            ],
            ["Processing Time:", f"{report_data.processing_time:.1f}s"],
            ["Throughput:", f"{report_data.throughput:.1f} patches/sec"],
        ]

        if report_data.memory_usage_gb > 0:
            data.append(["Peak Memory Usage:", f"{report_data.memory_usage_gb:.2f} GB"])

        table = Table(data, colWidths=[2.5 * inch, 2.5 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#555555")),
                    ("ALIGN", (0, 0), (0, -1), "RIGHT"),
                    ("ALIGN", (1, 0), (1, -1), "LEFT"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ]
            )
        )

        elements.append(table)
        elements.append(Spacer(1, 0.3 * inch))

        return elements

    def _build_metadata_section(self, report_data: StreamingReportData) -> List:
        """Build processing metadata section."""
        elements = []

        elements.append(Paragraph("Processing Metadata", self.styles["SectionHeader"]))

        data = [
            ["Model Version:", report_data.model_version],
            ["Processing Mode:", report_data.processing_mode.capitalize()],
            ["Analysis Timestamp:", report_data.report_timestamp.strftime("%Y-%m-%d %H:%M:%S UTC")],
        ]

        table = Table(data, colWidths=[2.5 * inch, 3.5 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#666666")),
                    ("ALIGN", (0, 0), (0, -1), "RIGHT"),
                    ("ALIGN", (1, 0), (1, -1), "LEFT"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )

        elements.append(table)
        elements.append(Spacer(1, 0.3 * inch))

        return elements

    def _build_clinical_notes(self, report_data: StreamingReportData) -> List:
        """Build clinical notes and recommendations section."""
        elements = []

        elements.append(Paragraph("Clinical Notes", self.styles["SectionHeader"]))

        if report_data.physician_notes:
            elements.append(
                Paragraph(
                    f"<b>Physician Notes:</b><br/>{report_data.physician_notes}",
                    self.styles["Normal"],
                )
            )
            elements.append(Spacer(1, 0.1 * inch))

        if report_data.recommendations:
            elements.append(Paragraph("<b>Recommendations:</b>", self.styles["Normal"]))
            for i, rec in enumerate(report_data.recommendations, 1):
                elements.append(Paragraph(f"{i}. {rec}", self.styles["Normal"]))

        elements.append(Spacer(1, 0.3 * inch))

        return elements

    def _build_footer(self, report_data: StreamingReportData) -> List:
        """Build report footer with disclaimers."""
        elements = []

        elements.append(Spacer(1, 0.5 * inch))

        disclaimer = """
        <i><font size=8>
        DISCLAIMER: This report is generated by an AI-assisted diagnostic system and should be used 
        as a decision support tool only. All results must be reviewed and validated by a qualified 
        healthcare professional. This system is not intended to replace clinical judgment.
        </font></i>
        """

        elements.append(Paragraph(disclaimer, self.styles["Normal"]))

        return elements

    def generate_html_report(self, report_data: StreamingReportData, output_path: Path) -> Path:
        """Generate HTML clinical report.

        Args:
            report_data: Report data with results and visualizations
            output_path: Path to save HTML report

        Returns:
            Path to generated HTML file
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Build HTML content
        html_content = self._build_html_content(report_data)

        # Write to file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        logger.info(f"Generated HTML report: {output_path}")
        return output_path

    def _build_html_content(self, report_data: StreamingReportData) -> str:
        """Build HTML report content."""
        # Confidence color
        if report_data.confidence >= 0.90:
            conf_color = "#2e7d32"
        elif report_data.confidence >= 0.70:
            conf_color = "#f57c00"
        else:
            conf_color = "#c62828"

        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WSI Analysis Report - {report_data.slide_id}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 900px;
            margin: 40px auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .container {{
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }}
        .header {{
            text-align: center;
            border-bottom: 3px solid #2c5aa0;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            color: #1a1a1a;
            margin: 0;
        }}
        .header h2 {{
            color: #666;
            font-weight: normal;
            margin: 10px 0 0 0;
        }}
        .section {{
            margin: 30px 0;
        }}
        .section-title {{
            color: #2c5aa0;
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 15px;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 5px;
        }}
        .info-table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        .info-table td {{
            padding: 8px;
            border-bottom: 1px solid #e0e0e0;
        }}
        .info-table td:first-child {{
            font-weight: bold;
            color: #555;
            width: 200px;
        }}
        .confidence {{
            font-size: 24px;
            font-weight: bold;
            color: {conf_color};
            margin: 10px 0;
        }}
        .visualization {{
            text-align: center;
            margin: 20px 0;
        }}
        .visualization img {{
            max-width: 100%;
            border: 1px solid #ddd;
            border-radius: 4px;
        }}
        .visualization-caption {{
            font-style: italic;
            color: #666;
            margin-top: 10px;
        }}
        .disclaimer {{
            background: #fff3cd;
            border: 1px solid #ffc107;
            border-radius: 4px;
            padding: 15px;
            margin-top: 30px;
            font-size: 12px;
            color: #856404;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{self.institution_name}</h1>
            <h2>Real-Time WSI Analysis Report</h2>
        </div>
        
        <div class="section">
            <div class="section-title">Slide Information</div>
            <table class="info-table">
                <tr>
                    <td>Slide ID:</td>
                    <td>{report_data.slide_id}</td>
                </tr>
                <tr>
                    <td>Report Date:</td>
                    <td>{report_data.report_timestamp.strftime('%Y-%m-%d %H:%M:%S')}</td>
                </tr>
            </table>
        </div>
        
        <div class="section">
            <div class="section-title">Analysis Results</div>
            <p><strong>Prediction:</strong> {report_data.prediction_class}</p>
            <div class="confidence">Confidence: {report_data.confidence*100:.1f}%</div>
        </div>
        
        <div class="section">
            <div class="section-title">Quality Metrics</div>
            <table class="info-table">
                <tr>
                    <td>Coverage:</td>
                    <td>{report_data.coverage_percent:.1f}%</td>
                </tr>
                <tr>
                    <td>Patches Processed:</td>
                    <td>{report_data.patches_processed:,} / {report_data.total_patches:,}</td>
                </tr>
                <tr>
                    <td>Processing Time:</td>
                    <td>{report_data.processing_time:.1f}s</td>
                </tr>
                <tr>
                    <td>Throughput:</td>
                    <td>{report_data.throughput:.1f} patches/sec</td>
                </tr>
            </table>
        </div>
        
        <div class="disclaimer">
            <strong>DISCLAIMER:</strong> This report is generated by an AI-assisted diagnostic system 
            and should be used as a decision support tool only. All results must be reviewed and 
            validated by a qualified healthcare professional.
        </div>
    </div>
</body>
</html>
"""

        return html
