apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pathology-models-pvc
  namespace: pathology
  labels:
    app: pathology-api
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pathology-data-pvc
  namespace: pathology
  labels:
    app: pathology-api
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
