"""
Integration tests for WSI processing pipeline with existing HistoCore components.

This test suite verifies that HDF5 files generated by the WSI processing pipeline
are fully compatible with existing CAMELYONSlideDataset, CAMELYONPatchDataset,
and training/evaluation workflows.

Test Coverage:
- Task 13.1: HDF5 compatibility with CAMELYONSlideDataset
- Task 13.2: HDF5 compatibility with CAMELYONPatchDataset
- Task 13.3: Integration with training scripts
- Task 13.4: Integration with evaluation scripts
"""

import json
import tempfile
from pathlib import Path

import h5py
import numpy as np
import pytest
import torch

from src.data.camelyon_dataset import (
    CAMELYONPatchDataset,
    CAMELYONSlideDataset,
    CAMELYONSlideIndex,
    SlideMetadata,
    collate_slide_bags,
    validate_feature_file,
)
from src.data.wsi_pipeline.cache import FeatureCache


@pytest.fixture
def temp_dir():
    """Create temporary directory for test files."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def sample_features():
    """Generate sample features and coordinates."""
    num_patches = 100
    feature_dim = 512
    features = np.random.randn(num_patches, feature_dim).astype(np.float32)
    coordinates = np.random.randint(0, 10000, size=(num_patches, 2)).astype(np.int32)
    return features, coordinates


@pytest.fixture
def sample_slide_index(temp_dir):
    """Create sample slide index with metadata."""
    slides = [
        SlideMetadata(
            slide_id="slide_001",
            patient_id="patient_001",
            file_path="slide_001.svs",
            label=1,
            split="train",
            width=50000,
            height=50000,
            magnification=40.0,
            mpp=0.25,
        ),
        SlideMetadata(
            slide_id="slide_002",
            patient_id="patient_002",
            file_path="slide_002.svs",
            label=0,
            split="val",
            width=60000,
            height=60000,
            magnification=40.0,
            mpp=0.25,
        ),
        SlideMetadata(
            slide_id="slide_003",
            patient_id="patient_003",
            file_path="slide_003.svs",
            label=1,
            split="test",
            width=55000,
            height=55000,
            magnification=40.0,
            mpp=0.25,
        ),
    ]

    index = CAMELYONSlideIndex(slides)
    index_path = temp_dir / "slide_index.json"
    index.save(index_path)

    return index, index_path


@pytest.fixture
def cached_features(temp_dir, sample_features, sample_slide_index):
    """Create cached HDF5 features using FeatureCache."""
    features, coordinates = sample_features
    index, _ = sample_slide_index

    features_dir = temp_dir / "features"
    cache = FeatureCache(cache_dir=features_dir, compression="gzip")

    # Cache features for all slides
    for slide in index.slides:
        metadata = {
            "patient_id": slide.patient_id,
            "magnification": slide.magnification,
            "mpp": slide.mpp,
            "patch_size": 256,
            "stride": 256,
            "level": 0,
            "encoder_name": "resnet50",
        }
        cache.save_features(
            slide_id=slide.slide_id,
            features=features,
            coordinates=coordinates,
            metadata=metadata,
        )

    return features_dir, features, coordinates


class TestHDF5Compatibility:
    """Test HDF5 file compatibility with existing dataset classes."""

    def test_hdf5_structure_validation(self, cached_features):
        """Verify HDF5 files have correct structure for dataset classes."""
        features_dir, expected_features, expected_coords = cached_features

        # Test validation function
        result = validate_feature_file(features_dir / "slide_001.h5")

        assert result["valid"] is True
        assert result["error"] is None
        assert result["num_patches"] == expected_features.shape[0]
        assert result["feature_dim"] == expected_features.shape[1]

    def test_hdf5_datasets_exist(self, cached_features):
        """Verify required datasets exist in HDF5 files."""
        features_dir, _, _ = cached_features

        with h5py.File(features_dir / "slide_001.h5", "r") as f:
            assert "features" in f
            assert "coordinates" in f

            # Check shapes
            assert f["features"].ndim == 2
            assert f["coordinates"].ndim == 2
            assert f["coordinates"].shape[1] == 2

            # Check data types
            assert f["features"].dtype == np.float32
            assert f["coordinates"].dtype == np.int32

    def test_hdf5_metadata_attributes(self, cached_features):
        """Verify metadata attributes are stored correctly."""
        features_dir, _, _ = cached_features

        with h5py.File(features_dir / "slide_001.h5", "r") as f:
            # Check required metadata attributes
            assert "slide_id" in f.attrs
            assert "patient_id" in f.attrs
            assert "patch_size" in f.attrs
            assert "encoder_name" in f.attrs
            assert "num_patches" in f.attrs

            # Verify values
            assert f.attrs["slide_id"] == "slide_001"
            assert f.attrs["patch_size"] == 256
            assert f.attrs["encoder_name"] == "resnet50"


class TestCAMELYONSlideDatasetIntegration:
    """Test integration with CAMELYONSlideDataset (Task 13.1)."""

    def test_dataset_initialization(self, cached_features, sample_slide_index):
        """Test CAMELYONSlideDataset can load processed HDF5 files."""
        features_dir, _, _ = cached_features
        index, _ = sample_slide_index

        # Create dataset for train split
        dataset = CAMELYONSlideDataset(
            slide_index=index,
            features_dir=features_dir,
            split="train",
        )

        assert len(dataset) == 1  # Only 1 train slide
        assert dataset.split == "train"

    def test_dataset_getitem(self, cached_features, sample_slide_index):
        """Test loading individual slides from dataset."""
        features_dir, expected_features, expected_coords = cached_features
        index, _ = sample_slide_index

        dataset = CAMELYONSlideDataset(
            slide_index=index,
            features_dir=features_dir,
            split="train",
        )

        # Get first slide
        sample = dataset[0]

        # Verify structure
        assert "slide_id" in sample
        assert "patient_id" in sample
        assert "label" in sample
        assert "features" in sample
        assert "coordinates" in sample
        assert "num_patches" in sample

        # Verify data types
        assert isinstance(sample["features"], torch.Tensor)
        assert isinstance(sample["coordinates"], torch.Tensor)
        assert sample["features"].dtype == torch.float32
        assert sample["coordinates"].dtype == torch.int32

        # Verify shapes
        assert sample["features"].shape == (expected_features.shape[0], expected_features.shape[1])
        assert sample["coordinates"].shape == (expected_coords.shape[0], 2)
        assert sample["num_patches"] == expected_features.shape[0]

    def test_dataset_metadata_access(self, cached_features, sample_slide_index):
        """Test metadata is accessible from loaded samples."""
        features_dir, _, _ = cached_features
        index, _ = sample_slide_index

        dataset = CAMELYONSlideDataset(
            slide_index=index,
            features_dir=features_dir,
            split="train",
        )

        sample = dataset[0]

        assert sample["slide_id"] == "slide_001"
        assert sample["patient_id"] == "patient_001"
        assert sample["label"] == 1

    def test_collate_slide_bags(self, cached_features, sample_slide_index):
        """Test collate function works with processed features."""
        features_dir, _, _ = cached_features
        index, _ = sample_slide_index

        # Create dataset with multiple slides
        dataset = CAMELYONSlideDataset(
            slide_index=index,
            features_dir=features_dir,
            split="val",
        )

        # Get samples
        samples = [dataset[i] for i in range(len(dataset))]

        # Collate
        batch = collate_slide_bags(samples)

        # Verify batch structure
        assert "features" in batch
        assert "coordinates" in batch
        assert "labels" in batch
        assert "num_patches" in batch
        assert "slide_ids" in batch
        assert "patient_ids" in batch

        # Verify shapes
        assert batch["features"].ndim == 3  # [batch_size, max_patches, feature_dim]
        assert batch["coordinates"].ndim == 3  # [batch_size, max_patches, 2]
        assert batch["labels"].ndim == 1  # [batch_size]
        assert batch["num_patches"].ndim == 1  # [batch_size]


class TestCAMELYONPatchDatasetIntegration:
    """Test integration with CAMELYONPatchDataset (Task 13.2)."""

    def test_patch_dataset_initialization(self, cached_features, sample_slide_index):
        """Test CAMELYONPatchDataset can load processed HDF5 files."""
        features_dir, expected_features, _ = cached_features
        index, _ = sample_slide_index

        dataset = CAMELYONPatchDataset(
            slide_index=index,
            features_dir=features_dir,
            split="train",
        )

        # Should have num_patches patches from train slides
        assert len(dataset) == expected_features.shape[0]

    def test_patch_dataset_getitem(self, cached_features, sample_slide_index):
        """Test loading individual patches from dataset."""
        features_dir, expected_features, _ = cached_features
        index, _ = sample_slide_index

        dataset = CAMELYONPatchDataset(
            slide_index=index,
            features_dir=features_dir,
            split="train",
        )

        # Get first patch
        sample = dataset[0]

        # Verify structure
        assert "features" in sample
        assert "coordinates" in sample
        assert "slide_id" in sample
        assert "patient_id" in sample
        assert "label" in sample
        assert "patch_idx" in sample

        # Verify data types
        assert isinstance(sample["features"], torch.Tensor)
        assert isinstance(sample["coordinates"], torch.Tensor)
        assert sample["features"].dtype == torch.float32
        assert sample["coordinates"].dtype == torch.int32

        # Verify shapes
        assert sample["features"].ndim == 1  # [feature_dim]
        assert sample["features"].shape[0] == expected_features.shape[1]
        assert sample["coordinates"].shape == (2,)

    def test_patch_dataset_slide_features(self, cached_features, sample_slide_index):
        """Test get_slide_features method."""
        features_dir, expected_features, _ = cached_features
        index, _ = sample_slide_index

        dataset = CAMELYONPatchDataset(
            slide_index=index,
            features_dir=features_dir,
            split="train",
        )

        # Get all features for a slide
        slide_features = dataset.get_slide_features("slide_001")

        assert slide_features is not None
        assert isinstance(slide_features, torch.Tensor)
        assert slide_features.shape == (expected_features.shape[0], expected_features.shape[1])

    def test_patch_dataset_aggregation(self, cached_features, sample_slide_index):
        """Test aggregate_slide_features method."""
        features_dir, expected_features, _ = cached_features
        index, _ = sample_slide_index

        dataset = CAMELYONPatchDataset(
            slide_index=index,
            features_dir=features_dir,
            split="train",
        )

        # Test mean aggregation
        mean_features = dataset.aggregate_slide_features("slide_001", method="mean")
        assert mean_features is not None
        assert mean_features.shape == (expected_features.shape[1],)

        # Test max aggregation
        max_features = dataset.aggregate_slide_features("slide_001", method="max")
        assert max_features is not None
        assert max_features.shape == (expected_features.shape[1],)


class TestTrainingScriptIntegration:
    """Test integration with training scripts (Task 13.3)."""

    def test_dataloader_creation(self, cached_features, sample_slide_index):
        """Test creating DataLoader with processed features."""
        from torch.utils.data import DataLoader

        features_dir, _, _ = cached_features
        index, _ = sample_slide_index

        dataset = CAMELYONSlideDataset(
            slide_index=index,
            features_dir=features_dir,
            split="train",
        )

        # Create DataLoader
        dataloader = DataLoader(
            dataset,
            batch_size=2,
            shuffle=True,
            collate_fn=collate_slide_bags,
        )

        # Test iteration
        for batch in dataloader:
            assert "features" in batch
            assert "labels" in batch
            assert batch["features"].ndim == 3
            break  # Just test first batch

    def test_model_forward_pass(self, cached_features, sample_slide_index):
        """Test model forward pass with processed features."""
        import torch.nn as nn
        from torch.utils.data import DataLoader

        features_dir, expected_features, _ = cached_features
        index, _ = sample_slide_index

        dataset = CAMELYONSlideDataset(
            slide_index=index,
            features_dir=features_dir,
            split="train",
        )

        dataloader = DataLoader(
            dataset,
            batch_size=1,
            collate_fn=collate_slide_bags,
        )

        # Create simple model
        feature_dim = expected_features.shape[1]
        model = nn.Sequential(
            nn.Linear(feature_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 1),
        )

        # Test forward pass
        for batch in dataloader:
            features = batch["features"]  # [batch_size, max_patches, feature_dim]
            num_patches = batch["num_patches"]

            # Mean pooling
            mask = torch.arange(features.size(1))[None, :] < num_patches[:, None]
            mask = mask.unsqueeze(-1).float()
            pooled = (features * mask).sum(dim=1) / num_patches.unsqueeze(-1).float()

            # Forward pass
            output = model(pooled)

            assert output.shape == (1, 1)
            break


class TestEvaluationScriptIntegration:
    """Test integration with evaluation scripts (Task 13.4)."""

    def test_slide_level_inference(self, cached_features, sample_slide_index):
        """Test slide-level inference with processed features."""
        import torch.nn as nn

        features_dir, expected_features, _ = cached_features
        index, _ = sample_slide_index

        # Create simple model
        feature_dim = expected_features.shape[1]
        model = nn.Sequential(
            nn.Linear(feature_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 1),
        )
        model.eval()

        # Load slide features
        slide = index.slides[0]
        feature_file = features_dir / f"{slide.slide_id}.h5"

        with h5py.File(feature_file, "r") as f:
            features = torch.tensor(f["features"][:], dtype=torch.float32)
            coordinates = torch.tensor(f["coordinates"][:], dtype=torch.int32)

        # Add batch dimension
        features = features.unsqueeze(0)

        # Mean pooling
        pooled = features.mean(dim=1)

        # Inference
        with torch.no_grad():
            logits = model(pooled)
            prob = torch.sigmoid(logits).item()

        assert 0.0 <= prob <= 1.0

    def test_metrics_computation(self, cached_features, sample_slide_index):
        """Test metrics computation with processed features."""
        from sklearn.metrics import accuracy_score, roc_auc_score

        features_dir, _, _ = cached_features
        index, _ = sample_slide_index

        # Simulate predictions
        predictions = []
        probabilities = []
        labels = []

        for slide in index.slides:
            feature_file = features_dir / f"{slide.slide_id}.h5"
            if not feature_file.exists():
                continue

            # Simulate prediction
            pred = np.random.randint(0, 2)
            prob = np.random.random()

            predictions.append(pred)
            probabilities.append(prob)
            labels.append(slide.label)

        predictions = np.array(predictions)
        probabilities = np.array(probabilities)
        labels = np.array(labels)

        # Compute metrics
        accuracy = accuracy_score(labels, predictions)

        # Only compute AUC if we have both classes
        if len(np.unique(labels)) >= 2:
            auc = roc_auc_score(labels, probabilities)
            assert 0.0 <= auc <= 1.0

        assert 0.0 <= accuracy <= 1.0


class TestEndToEndWorkflow:
    """Test complete end-to-end workflow."""

    def test_complete_pipeline(self, temp_dir):
        """Test complete pipeline from feature caching to model training."""
        # 1. Create slide index
        slides = [
            SlideMetadata(
                slide_id=f"slide_{i:03d}",
                patient_id=f"patient_{i:03d}",
                file_path=f"slide_{i:03d}.svs",
                label=i % 2,
                split="train" if i < 3 else "val",
                width=50000,
                height=50000,
                magnification=40.0,
                mpp=0.25,
            )
            for i in range(5)
        ]

        index = CAMELYONSlideIndex(slides)
        index_path = temp_dir / "slide_index.json"
        index.save(index_path)

        # 2. Cache features
        features_dir = temp_dir / "features"
        cache = FeatureCache(cache_dir=features_dir, compression="gzip")

        for slide in slides:
            features = np.random.randn(50, 512).astype(np.float32)
            coordinates = np.random.randint(0, 10000, size=(50, 2)).astype(np.int32)

            metadata = {
                "patient_id": slide.patient_id,
                "magnification": slide.magnification,
                "mpp": slide.mpp,
                "patch_size": 256,
                "stride": 256,
                "level": 0,
                "encoder_name": "resnet50",
            }

            cache.save_features(
                slide_id=slide.slide_id,
                features=features,
                coordinates=coordinates,
                metadata=metadata,
            )

        # 3. Create datasets
        train_dataset = CAMELYONSlideDataset(
            slide_index=index,
            features_dir=features_dir,
            split="train",
        )

        val_dataset = CAMELYONSlideDataset(
            slide_index=index,
            features_dir=features_dir,
            split="val",
        )

        assert len(train_dataset) == 3
        assert len(val_dataset) == 2

        # 4. Create dataloaders
        from torch.utils.data import DataLoader

        train_loader = DataLoader(
            train_dataset,
            batch_size=2,
            shuffle=True,
            collate_fn=collate_slide_bags,
        )

        val_loader = DataLoader(
            val_dataset,
            batch_size=2,
            shuffle=False,
            collate_fn=collate_slide_bags,
        )

        # 5. Test training loop
        import torch.nn as nn
        import torch.optim as optim

        model = nn.Sequential(
            nn.Linear(512, 128),
            nn.ReLU(),
            nn.Linear(128, 1),
        )

        optimizer = optim.Adam(model.parameters(), lr=0.001)
        criterion = nn.BCEWithLogitsLoss()

        # Train for 1 epoch
        model.train()
        for batch in train_loader:
            features = batch["features"]
            labels = batch["labels"].float()
            num_patches = batch["num_patches"]

            # Mean pooling
            mask = torch.arange(features.size(1))[None, :] < num_patches[:, None]
            mask = mask.unsqueeze(-1).float()
            pooled = (features * mask).sum(dim=1) / num_patches.unsqueeze(-1).float()

            # Forward pass
            optimizer.zero_grad()
            logits = model(pooled).squeeze(-1)  # Remove last dimension only

            # Ensure shapes match for loss
            if logits.ndim == 0:
                logits = logits.unsqueeze(0)
            if labels.ndim == 0:
                labels = labels.unsqueeze(0)

            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()

        # 6. Test evaluation
        model.eval()
        all_preds = []
        all_labels = []

        with torch.no_grad():
            for batch in val_loader:
                features = batch["features"]
                labels = batch["labels"]
                num_patches = batch["num_patches"]

                # Mean pooling
                mask = torch.arange(features.size(1))[None, :] < num_patches[:, None]
                mask = mask.unsqueeze(-1).float()
                pooled = (features * mask).sum(dim=1) / num_patches.unsqueeze(-1).float()

                # Forward pass
                logits = model(pooled).squeeze(-1)  # Remove last dimension only

                # Ensure logits is 1D
                if logits.ndim == 0:
                    logits = logits.unsqueeze(0)

                preds = (torch.sigmoid(logits) > 0.5).long()

                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(labels.cpu().numpy())

        # Verify we got predictions
        assert len(all_preds) == len(val_dataset)
        assert len(all_labels) == len(val_dataset)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
