"""
Property-based tests for task-aware batch samplers.

Tests universal correctness properties for BalancedBatchSampler,
RegressionBatchSampler, and SurvivalBatchSampler using Hypothesis.
"""

from collections import Counter

import pytest
import torch

from hypothesis import assume, given, settings
from hypothesis import strategies as st
from src.data.batch_samplers import (
    BalancedBatchSampler,
    RegressionBatchSampler,
    SurvivalBatchSampler,
)


class TestBalancedBatchSamplerProperties:
    """Property tests for BalancedBatchSampler."""

    @given(
        labels=st.lists(
            st.integers(min_value=0, max_value=4), min_size=10, max_size=100  # 5 classes max
        ),
        batch_size=st.integers(min_value=2, max_value=20),
        shuffle=st.booleans(),
    )
    @settings(max_examples=50)
    def test_property_13_balanced_batch_composition(self, labels, batch_size, shuffle):
        """
        Property 13: Balanced Batch Composition

        For any batch generated by BalancedBatchSampler, the class distribution
        should be approximately balanced (no class should dominate).

        Validates: Requirements 4.1
        """
        # Skip if batch_size > dataset size (would cause infinite loop)
        assume(batch_size <= len(labels))

        # Skip edge cases where batch_size is too small for meaningful balance
        num_classes = len(set(labels))
        assume(batch_size >= num_classes)  # Need at least one sample per class

        # Create sampler
        sampler = BalancedBatchSampler(
            labels=torch.tensor(labels), batch_size=batch_size, shuffle=shuffle
        )

        # Get first batch
        batch = next(iter(sampler))

        # Count classes in batch
        batch_labels = [labels[idx] for idx in batch]
        class_counts = Counter(batch_labels)

        # Property: No class should have more than 3x the minimum count
        # (more lenient for small batches and imbalanced datasets)
        min_count = min(class_counts.values())
        max_count = max(class_counts.values())

        # Allow up to 3x imbalance (reasonable for oversampling)
        max_allowed_ratio = 3.0

        assert max_count <= min_count * max_allowed_ratio, (
            f"Excessive class imbalance: max_count={max_count}, "
            f"min_count={min_count}, ratio={max_count/min_count:.2f}, "
            f"max_allowed_ratio={max_allowed_ratio}"
        )

    @given(
        # Create imbalanced dataset: majority class has 3x more samples
        majority_size=st.integers(min_value=15, max_value=30),
        minority_size=st.integers(min_value=5, max_value=10),
        batch_size=st.integers(min_value=4, max_value=12),
    )
    @settings(max_examples=30)
    def test_property_14_minority_class_oversampling(
        self, majority_size, minority_size, batch_size
    ):
        """
        Property 14: Minority Class Oversampling

        When dataset is imbalanced, minority classes should appear in batches
        through oversampling (sampling with replacement).

        Validates: Requirements 4.2
        """
        # Create imbalanced dataset
        labels = [0] * majority_size + [1] * minority_size

        # Skip if batch_size > dataset size
        assume(batch_size <= len(labels))

        sampler = BalancedBatchSampler(
            labels=torch.tensor(labels), batch_size=batch_size, shuffle=True
        )

        # Generate multiple batches to test oversampling
        minority_appearances = 0
        total_batches = min(5, len(sampler))  # Test up to 5 batches

        for i, batch in enumerate(sampler):
            if i >= total_batches:
                break

            batch_labels = [labels[idx] for idx in batch]
            minority_count = batch_labels.count(1)
            minority_appearances += minority_count

        # Property: Minority class should appear in batches despite being rare
        # With oversampling, minority class should appear at least once per batch on average
        expected_minority_per_batch = batch_size / 2  # Balanced sampling
        total_expected = expected_minority_per_batch * total_batches

        # Allow some tolerance (at least 50% of expected)
        min_expected = total_expected * 0.5

        assert minority_appearances >= min_expected, (
            f"Insufficient minority class oversampling: "
            f"appearances={minority_appearances}, "
            f"min_expected={min_expected}, "
            f"total_expected={total_expected}"
        )

    @given(
        labels=st.lists(
            st.integers(min_value=0, max_value=2), min_size=15, max_size=50  # 3 classes
        ),
        batch_size=st.integers(min_value=6, max_value=15),
    )
    @settings(max_examples=30)
    def test_property_15_minimum_class_representation(self, labels, batch_size):
        """
        Property 15: Minimum Class Representation

        Each class present in the dataset should appear at least once
        in every batch (when batch_size >= num_classes).

        Validates: Requirements 4.5
        """
        # Skip if batch_size > dataset size
        assume(batch_size <= len(labels))

        # Only test when batch_size >= num_classes (otherwise impossible)
        unique_classes = set(labels)
        assume(batch_size >= len(unique_classes))

        sampler = BalancedBatchSampler(
            labels=torch.tensor(labels), batch_size=batch_size, shuffle=True
        )

        # Test first batch
        batch = next(iter(sampler))
        batch_labels = [labels[idx] for idx in batch]
        batch_classes = set(batch_labels)

        # Property: All classes should be represented in the batch
        missing_classes = unique_classes - batch_classes

        assert len(missing_classes) == 0, (
            f"Missing classes in batch: {missing_classes}, "
            f"batch_classes={batch_classes}, "
            f"all_classes={unique_classes}"
        )


class TestRegressionBatchSamplerProperties:
    """Property tests for RegressionBatchSampler."""

    @given(
        targets=st.lists(
            st.floats(min_value=0.0, max_value=10.0, allow_nan=False, allow_infinity=False),
            min_size=20,
            max_size=100,
        ),
        batch_size=st.integers(min_value=4, max_value=20),
        num_bins=st.integers(min_value=2, max_value=10),
    )
    @settings(max_examples=30)
    def test_property_16_uniform_target_coverage(self, targets, batch_size, num_bins):
        """
        Property 16: Uniform Target Coverage

        Batches should contain samples from across the target range,
        not just from common target values.

        Validates: Requirements 4.1 (regression variant)
        """
        # Skip if batch_size > dataset size
        assume(batch_size <= len(targets))

        # Skip if all targets are the same (no range to cover)
        assume(len(set(targets)) > 1)

        sampler = RegressionBatchSampler(
            targets=torch.tensor(targets), batch_size=batch_size, num_bins=num_bins
        )

        # Get first batch
        batch = next(iter(sampler))
        batch_targets = [targets[idx] for idx in batch]

        # Property: Batch should span a reasonable portion of the target range
        min_target = min(targets)
        max_target = max(targets)
        target_range = max_target - min_target

        batch_min = min(batch_targets)
        batch_max = max(batch_targets)
        batch_range = batch_max - batch_min

        # Batch should cover at least 25% of the total range (with some bins)
        min_coverage = target_range * 0.25

        assert batch_range >= min_coverage, (
            f"Insufficient target range coverage: "
            f"batch_range={batch_range:.3f}, "
            f"min_coverage={min_coverage:.3f}, "
            f"total_range={target_range:.3f}"
        )


class TestSurvivalBatchSamplerProperties:
    """Property tests for SurvivalBatchSampler."""

    @given(
        num_samples=st.integers(min_value=20, max_value=100),
        event_rate=st.floats(min_value=0.2, max_value=0.8),  # 20-80% event rate
        batch_size=st.integers(min_value=4, max_value=20),
    )
    @settings(max_examples=30)
    def test_property_17_balanced_event_rates(self, num_samples, event_rate, batch_size):
        """
        Property 17: Balanced Event Rates

        Batches should maintain balanced event rates (mix of events and censored),
        not be dominated by one type.

        Validates: Requirements 4.1 (survival variant)
        """
        # Skip if batch_size > dataset size
        assume(batch_size <= num_samples)

        # Generate synthetic survival data
        times = torch.rand(num_samples) * 10  # Random times 0-10
        events = torch.bernoulli(torch.full((num_samples,), event_rate)).long()

        # Ensure we have both events and censored samples
        num_events = events.sum().item()
        num_censored = num_samples - num_events
        assume(num_events > 0 and num_censored > 0)

        sampler = SurvivalBatchSampler(times=times, events=events, batch_size=batch_size)

        # Get first batch
        batch = next(iter(sampler))
        batch_events = [events[idx].item() for idx in batch]

        # Count events and censored in batch
        batch_event_count = sum(batch_events)
        batch_censored_count = len(batch_events) - batch_event_count

        # Property: Both events and censored should be represented
        # (unless one type is extremely rare)
        min_representation = max(1, batch_size // 10)  # At least 10% or 1 sample

        if num_events >= min_representation and num_censored >= min_representation:
            assert (
                batch_event_count > 0
            ), f"No events in batch despite {num_events} events in dataset"
            assert (
                batch_censored_count > 0
            ), f"No censored samples in batch despite {num_censored} censored in dataset"

    @given(
        num_samples=st.integers(min_value=30, max_value=80),
        batch_size=st.integers(min_value=6, max_value=15),
    )
    @settings(max_examples=20)
    def test_property_18_temporal_diversity(self, num_samples, batch_size):
        """
        Property 18: Temporal Diversity

        Batches should contain samples from different time periods,
        not just early or late events.

        Validates: Requirements 4.1 (survival temporal aspect)
        """
        # Skip if batch_size > dataset size
        assume(batch_size <= num_samples)

        # Generate survival data with temporal structure
        times = torch.linspace(0.1, 10.0, num_samples)  # Evenly spaced times
        events = torch.ones(num_samples, dtype=torch.long)  # All events for simplicity

        sampler = SurvivalBatchSampler(times=times, events=events, batch_size=batch_size)

        # Get first batch
        batch = next(iter(sampler))
        batch_times = [times[idx].item() for idx in batch]

        # Property: Batch should span a reasonable portion of the time range
        min_time = times.min().item()
        max_time = times.max().item()
        time_range = max_time - min_time

        batch_min_time = min(batch_times)
        batch_max_time = max(batch_times)
        batch_time_range = batch_max_time - batch_min_time

        # Batch should cover at least 30% of the total time range
        min_coverage = time_range * 0.3

        assert batch_time_range >= min_coverage, (
            f"Insufficient temporal diversity: "
            f"batch_time_range={batch_time_range:.3f}, "
            f"min_coverage={min_coverage:.3f}, "
            f"total_time_range={time_range:.3f}"
        )


# Additional edge case tests
class TestBatchSamplerEdgeCases:
    """Test edge cases for all batch samplers."""

    def test_balanced_sampler_single_class(self):
        """Test BalancedBatchSampler with single class."""
        labels = [0] * 10
        sampler = BalancedBatchSampler(labels=torch.tensor(labels), batch_size=5)

        batch = next(iter(sampler))
        assert len(batch) == 5

        # All samples should be from the single class
        batch_labels = [labels[idx] for idx in batch]
        assert all(label == 0 for label in batch_labels)

    def test_regression_sampler_constant_targets(self):
        """Test RegressionBatchSampler with constant targets."""
        targets = [1.0] * 15
        sampler = RegressionBatchSampler(targets=torch.tensor(targets), batch_size=5)

        batch = next(iter(sampler))
        assert len(batch) == 5

        # All samples should have the same target
        batch_targets = [targets[idx] for idx in batch]
        assert all(target == 1.0 for target in batch_targets)

    def test_survival_sampler_all_events(self):
        """Test SurvivalBatchSampler with all events (no censoring)."""
        times = torch.rand(20) * 5
        events = torch.ones(20, dtype=torch.long)  # All events

        sampler = SurvivalBatchSampler(times=times, events=events, batch_size=8)

        batch = next(iter(sampler))
        assert len(batch) == 8

        # All samples should be events
        batch_events = [events[idx].item() for idx in batch]
        assert all(event == 1 for event in batch_events)

    def test_survival_sampler_all_censored(self):
        """Test SurvivalBatchSampler with all censored (no events)."""
        times = torch.rand(20) * 5
        events = torch.zeros(20, dtype=torch.long)  # All censored

        sampler = SurvivalBatchSampler(times=times, events=events, batch_size=8)

        batch = next(iter(sampler))
        assert len(batch) == 8

        # All samples should be censored
        batch_events = [events[idx].item() for idx in batch]
        assert all(event == 0 for event in batch_events)
