import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'When More Data Is Less Trustworthy',
  description: 'A technical report on site-signal alignment failure modes in federated computational pathology.',
  base: '/computational-pathology-research/',
  cleanUrls: true,
  lastUpdated: false,
  ignoreDeadLinks: true,
  srcExclude: [
    'ABOUT.md',
    'ANALYSIS_SYSTEM.md',
    'API_REFERENCE.md',
    'ARCHITECTURE.md',
    'ARCHITECTURE_MIGRATION.md',
    'AWS_AZURE_BAA_GUIDE.md',
    'BENCHMARK_SYSTEM.md',
    'CHANGELOG.md',
    'DOCS_INDEX.md',
    'EXPERIMENTS.md',
    'FAILURE_ANALYSIS.md',
    'FAIR_WEIGHTS_HYBRID_PROTOCOL.md',
    'FAIR_WEIGHTS_H_IMPLEMENTATION_STATUS.md',
    'FAIR_WEIGHTS_H_PCAM_FEDERATED_SMOKE_REPORT.md',
    'FAIR_WEIGHTS_H_SYNTHETIC_CAMELYON17_SMOKE_REPORT.md',
    'FAIR_WEIGHTS_H_SYNTHETIC_REPORT.md',
    'GETTING_STARTED.md',
    'PCAM_BENCHMARK_RESULTS.md',
    'PCAM_COMPARISON_GUIDE.md',
    'PCAM_CROSS_VALIDATION.md',
    'PCAM_FAILURE_ANALYSIS.md',
    'PCAM_FULLSCALE_GUIDE.md',
    'PCAM_REAL_RESULTS.md',
    'PERFORMANCE_COMPARISON.md',
    'PERFORMANCE.md',
    'PLATFORM_OVERVIEW.md',
    'REPOSITORY_OVERVIEW.md',
    'SECURITY_HARDENING.md',
    'TESTING_SUMMARY.md',
    'TRANSNNMIL_V2_ARCHITECTURE.md',
    'TRANSNNMIL_V2_STATUS.md',
    'TRANSNNMIL_V2_TRAINING.md',
    'archive/**',
    'api/**',
    'demo/**',
    'deployment/**',
    'diagrams/**',
    'federated_learning/**',
    'operations/**',
    'regulatory/**',
    'security/**',
    'training/**'
  ],
  themeConfig: {
    siteTitle: false,
    nav: [],
    sidebar: {},
    socialLinks: [],
    footer: {
      message: 'Independent technical report. Research-only; not clinical validation or diagnostic software.',
      copyright: 'Matthew Vaishnav'
    }
  },
  markdown: { math: true }
})