# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

import federated_learning_pb2 as federated__learning__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in federated_learning_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class FederatedLearningServiceStub(object):
    """Federated Learning Service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
            "/federated_learning.FederatedLearningService/RegisterClient",
            request_serializer=federated__learning__pb2.ClientRegistration.SerializeToString,
            response_deserializer=federated__learning__pb2.RegistrationResponse.FromString,
            _registered_method=True,
        )
        self.GetGlobalModel = channel.unary_unary(
            "/federated_learning.FederatedLearningService/GetGlobalModel",
            request_serializer=federated__learning__pb2.ModelRequest.SerializeToString,
            response_deserializer=federated__learning__pb2.ModelResponse.FromString,
            _registered_method=True,
        )
        self.SubmitUpdate = channel.unary_unary(
            "/federated_learning.FederatedLearningService/SubmitUpdate",
            request_serializer=federated__learning__pb2.ClientUpdateMessage.SerializeToString,
            response_deserializer=federated__learning__pb2.UpdateAcknowledgment.FromString,
            _registered_method=True,
        )
        self.GetRoundStatus = channel.unary_unary(
            "/federated_learning.FederatedLearningService/GetRoundStatus",
            request_serializer=federated__learning__pb2.RoundStatusRequest.SerializeToString,
            response_deserializer=federated__learning__pb2.RoundStatusResponse.FromString,
            _registered_method=True,
        )
        self.StartRound = channel.unary_unary(
            "/federated_learning.FederatedLearningService/StartRound",
            request_serializer=federated__learning__pb2.RoundStartMessage.SerializeToString,
            response_deserializer=federated__learning__pb2.RoundStartAcknowledgment.FromString,
            _registered_method=True,
        )


class FederatedLearningServiceServicer(object):
    """Federated Learning Service"""

    def RegisterClient(self, request, context):
        """Client registers with coordinator"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetGlobalModel(self, request, context):
        """Client requests global model for current round"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubmitUpdate(self, request, context):
        """Client submits local update"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRoundStatus(self, request, context):
        """Client checks round status"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StartRound(self, request, context):
        """Coordinator broadcasts round start"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FederatedLearningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RegisterClient": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterClient,
            request_deserializer=federated__learning__pb2.ClientRegistration.FromString,
            response_serializer=federated__learning__pb2.RegistrationResponse.SerializeToString,
        ),
        "GetGlobalModel": grpc.unary_unary_rpc_method_handler(
            servicer.GetGlobalModel,
            request_deserializer=federated__learning__pb2.ModelRequest.FromString,
            response_serializer=federated__learning__pb2.ModelResponse.SerializeToString,
        ),
        "SubmitUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.SubmitUpdate,
            request_deserializer=federated__learning__pb2.ClientUpdateMessage.FromString,
            response_serializer=federated__learning__pb2.UpdateAcknowledgment.SerializeToString,
        ),
        "GetRoundStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetRoundStatus,
            request_deserializer=federated__learning__pb2.RoundStatusRequest.FromString,
            response_serializer=federated__learning__pb2.RoundStatusResponse.SerializeToString,
        ),
        "StartRound": grpc.unary_unary_rpc_method_handler(
            servicer.StartRound,
            request_deserializer=federated__learning__pb2.RoundStartMessage.FromString,
            response_serializer=federated__learning__pb2.RoundStartAcknowledgment.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "federated_learning.FederatedLearningService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "federated_learning.FederatedLearningService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class FederatedLearningService(object):
    """Federated Learning Service"""

    @staticmethod
    def RegisterClient(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/federated_learning.FederatedLearningService/RegisterClient",
            federated__learning__pb2.ClientRegistration.SerializeToString,
            federated__learning__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetGlobalModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/federated_learning.FederatedLearningService/GetGlobalModel",
            federated__learning__pb2.ModelRequest.SerializeToString,
            federated__learning__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubmitUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/federated_learning.FederatedLearningService/SubmitUpdate",
            federated__learning__pb2.ClientUpdateMessage.SerializeToString,
            federated__learning__pb2.UpdateAcknowledgment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetRoundStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/federated_learning.FederatedLearningService/GetRoundStatus",
            federated__learning__pb2.RoundStatusRequest.SerializeToString,
            federated__learning__pb2.RoundStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StartRound(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/federated_learning.FederatedLearningService/StartRound",
            federated__learning__pb2.RoundStartMessage.SerializeToString,
            federated__learning__pb2.RoundStartAcknowledgment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
