"""
Application Constants

Centralized constants to avoid magic numbers throughout the codebase.
"""

# File Size Limits
MAX_FILE_SIZE_MB = 100
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
MAX_IMAGE_SIZE_MB = 50
MAX_IMAGE_SIZE_BYTES = MAX_IMAGE_SIZE_MB * 1024 * 1024

# String Length Limits
MAX_FILENAME_LENGTH = 255
MAX_EMAIL_LENGTH = 254  # RFC 5321
MAX_EMAIL_LOCAL_PART_LENGTH = 64  # RFC 5321
MAX_PASSWORD_LENGTH = 128
MIN_PASSWORD_LENGTH = 8
MAX_PATIENT_ID_LENGTH = 50
MAX_CASE_ID_LENGTH = 50

# Image Dimensions
MAX_IMAGE_WIDTH = 10000
MAX_IMAGE_HEIGHT = 10000
MIN_IMAGE_WIDTH = 1
MIN_IMAGE_HEIGHT = 1

# System Thresholds
CPU_USAGE_HIGH = 90
CPU_USAGE_MEDIUM = 70
MEMORY_USAGE_HIGH = 90
MEMORY_USAGE_MEDIUM = 80
DISK_USAGE_HIGH = 90
DISK_USAGE_MEDIUM = 80
GPU_UTILIZATION_HIGH = 90
GPU_UTILIZATION_MEDIUM = 80

# Rate Limiting
RATE_LIMIT_GLOBAL = "30/minute"
RATE_LIMIT_LOGIN = "5/minute"
RATE_LIMIT_REGISTER = "3/minute"
RATE_LIMIT_ANALYSIS = "10/minute"
RATE_LIMIT_READ = "100/minute"

# Timeouts
DEFAULT_REQUEST_TIMEOUT = 30  # seconds
DEFAULT_REGEX_TIMEOUT = 1  # seconds
DEFAULT_SESSION_TIMEOUT = 30  # minutes
LOCKOUT_DURATION = 900  # 15 minutes in seconds
LOCKOUT_THRESHOLD = 5  # failed attempts

# JSON Limits
MAX_JSON_SIZE_MB = 10.0
MAX_JSON_DEPTH = 20

# HTTP Status Codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_CONFLICT = 409
HTTP_TOO_MANY_REQUESTS = 429
HTTP_INTERNAL_ERROR = 500

# Logging
LOG_RETENTION_DAYS = 7 * 365  # 7 years for HIPAA
MAX_LOG_FILE_SIZE_MB = 100

# Coverage Thresholds
COVERAGE_LOW_THRESHOLD = 80
COVERAGE_MEDIUM_THRESHOLD = 90

# Performance Thresholds
MIN_GPU_MEMORY_GB = 10
MIN_DISK_SPACE_GB = 100
MAX_LATENCY_MS_GOOD = 50
MAX_LATENCY_MS_MEDIUM = 100

# Complexity Thresholds
MAX_CYCLOMATIC_COMPLEXITY = 10
MIN_CODE_QUALITY_SCORE = 60
